OT122-32
alkemyTech/OT122-Android pull request #14
Opened 2022-01-04 21:31 UTC by jeffamady

## Summary
-Call to the endpoint  "/api/news"
-News view model

2022-01-04 22:21 UTC, MelvinKucuk requested changes

2022-01-04 22:21 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/di/DataModule.kt
> +
aca te falto el `@Provides`

2022-01-04 22:21 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/HomeFragment.kt
> +                    Toast.makeText(this.context, "Oops! An error occurred", Toast.LENGTH_SHORT)
No usar string hardcodeados, usar los string resource

2022-01-05 17:15 UTC, jeffamady commented
Ya hice los cambios

2022-01-05 22:44 UTC, MelvinKucuk approved these changes, later dismissed

2022-01-06 23:47 UTC, MelvinKucuk approved these changes

2022-01-06 23:47 UTC, merged