OT122-44
alkemyTech/OT122-Android pull request #18
Opened 2022-01-05 20:13 UTC by FacuBayo

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT122/boards/184?modal=detail&selectedIssue=OT122-44&assignee=70121%3Acff407e4-8cb3-4aab-bc30-de4a895ebf38

Summary:

-Added Intent link redirection

2022-01-05 22:31 UTC, MelvinKucuk requested changes

2022-01-05 22:31 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/aboutus/AboutUsDetailsFragment.kt
> +        }
todo esto no es responsabilidad del onViewCreated() lo pasaria a un metodo aparte que su responsabilidad sea cargar los datos de la vista, para ahorrarte tantos `binding.` podes encerrar todo en `binding.apply { }`

2022-01-05 22:31 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/HomeFragment.kt
>  import android.view.View
este archivo no es parte del scope de la tarea

2022-01-05 22:32 UTC, MelvinKucuk requested changes

2022-01-05 22:32 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/aboutus/AboutUsDetailsFragment.kt
> +            startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(url)))
esto podrias pasarlo a un metodo que reciba un string y que su responsabilidad sea abrir el link

2022-01-05 22:33 UTC, MelvinKucuk commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
es necesaria este demendencia?

2022-01-05 23:13 UTC, FacuBayo commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Por alguna razón que desconozco se agregó sola cuando buildeo el gradle.

2022-01-05 23:14 UTC, FacuBayo commented on app/src/main/java/com/alkemy/ongsomosmas/ui/aboutus/AboutUsDetailsFragment.kt
> +        }
Me olvidé de borrarlos, cargué los datos para probar la pantalla.

2022-01-06 23:44 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/HomeFragment.kt
>          container: ViewGroup?,
este archivo no es parte del scope de la tarea

2022-01-06 23:44 UTC, MelvinKucuk approved these changes

2022-01-06 23:45 UTC, merged