OT122-49 News view
alkemyTech/OT122-Android pull request #21
Opened 2022-01-07 20:48 UTC by jeffamady

## Summary 
-News fragment 
-News recycler view
-Item news

2022-01-07 23:50 UTC, MelvinKucuk requested changes

2022-01-07 23:50 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/news/NewsFragment.kt
> +private const val ARG_PARAM2 = "param2"
si no se va a usar el codigo que viene en el template del fragment, sacarlo

2022-01-07 23:50 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/news/NewsFragment.kt
> + */
evitar comentarios del template

2022-01-07 23:50 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/news/NewsFragment.kt
> +        }
si no se va a usar el codigo que viene en el template del fragment, sacarlo

2022-01-07 23:50 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/news/NewsFragment.kt
> +    }
si no se va a usar el codigo que viene en el template del fragment, sacarlo, la creacion de la instacia esta bien pero no aplicarle los parametros que no va a usar

2022-01-08 01:05 UTC, jeffamady commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/news/NewsFragment.kt
> +    }
Dale gracias Melvin. La próxima lo saco directamente

2022-01-10 22:31 UTC, MelvinKucuk approved these changes

2022-01-10 22:31 UTC, merged