Ot122 30 Welcome Slide
alkemyTech/OT122-Android pull request #25
Opened 2022-01-11 12:29 UTC by sebapratto

add welcomeslide coneccion

2022-01-11 22:52 UTC, MelvinKucuk requested changes

2022-01-11 22:52 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/HomeFragment.kt
> +                }
la vista no deberia tener logica de este tipo, el contenedor Resource lo deberia resolver el viewModel y a la vista le deberia llegar la informacion que necesite para mostrar o ocultar datos

2022-01-11 22:52 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/welcome/WelcomeViewModel.kt
> +class WelcomeViewModel @ViewModelInject constructor(private val welcomeRepository: WelcomeRepository) :
hiciste el useCase pero no lo usaste en el ViewModel

2022-01-12 17:26 UTC, sebapratto commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/welcome/WelcomeViewModel.kt
> +class WelcomeViewModel @ViewModelInject constructor(private val welcomeRepository: WelcomeRepository) :
resuelto el caso de uso

2022-01-12 17:27 UTC, sebapratto commented on app/src/main/java/com/alkemy/ongsomosmas/ui/home/HomeFragment.kt
> +                }
esta logica esta en todo el proyecto, podriamos ver como seria la forma correcta?

2022-01-13 00:57 UTC, MelvinKucuk approved these changes

2022-01-13 00:57 UTC, merged